# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180629_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.BooleanField(default=False),
        ),
    ]
